const express = require('express');
const app = express();
const bcrypt = require('bcrypt');

//technique 1

const saltRounds = 10;
const myPass='password123';
const myPass2='password123';

let hashedPassword='';
let hashedPassword2='';

app.get('/user1', (req, res) => {
  bcrypt.genSalt(saltRounds,(err, salt)=>{
    // console.log(salt); //salt generated by byscrypt.genSalt
    bcrypt.hash(myPass,salt,(err, hash)=>{
      hashedPassword=hash;
    });
  });
  res.send('user1 created');
});

app.get('/user2',(req,res)=>{
  bcrypt.hash(myPass2,10,(err,hash)=>{
    hashedPassword2=hash;
  })
  res.send('user2 created');
})
app.get('/compare',(req,res)=>{
  bcrypt.compare(myPass2,hashedPassword2,(err, result)=>{
    console.log('result:',result);
  })
})
app.listen(3000, () => {
  console.log('server running');
  
});